In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# cd sample_data

/content/sample_data


In [6]:
# from google.colab import files
# upload = files.upload()

In [7]:
data_set = pd.read_csv('glen.csv')

**One Hot Encoding**

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data_encod = data_set
data_encod.DWD = le.fit_transform(data_encod.DWD)
data_encod.name = le.fit_transform(data_encod.name)
data_encod.wd_description = le.fit_transform(data_encod.wd_description)
data_encod.overlay_parents = le.fit_transform(data_encod.overlay_parents)
# data_encod

X = data_encod[['DWD','wd_description', 'overlay_parents']].values
y = data_encod.name.values

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
# ct = ColumnTransformer([(OneHotEncoder(), [0,1,2])], remainder = 'passthrough')
# ct = ColumnTransformer()
ct = ColumnTransformer(
                       [("imputer", SimpleImputer(missing_values=np.nan, strategy='median'), [2]),
                        ("one_hot", OneHotEncoder(categories='auto', sparse=False), slice(0, 1, 2))])

X = ct.fit_transform(X)

X = X[:,0:4]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


**Support Vector Machine (SVM)**

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [14]:
# X = data_set.drop(['name'], axis = 'columns')
# y = data_set.name

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

In [21]:
model = SVC(kernel = 'linear', C = 1)    #linear, polynomial, Gaussian or radial basis, sigmoid

In [22]:
model.fit(X_train, y_train)
svm_pred = model.predict(X_test)
accuracy = model.score(X_test, y_test)

In [23]:
print(accuracy)

0.0


In [24]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, svm_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
